version: "3.9"

services:
  dash-app:
    build: .
    container_name: howistheweather
    ports:
      - "8050:8050"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
