city_ids = [
    "btn-warszawa",
    "btn-wrocław",
    "btn-poznań",
    "btn-kraków",
    "btn-gdańsk",
    "btn-szczecin",
]

city_names = [
    "Warszawa",
    "Wrocław",
    "Poznań",
    "Kraków",
    "Gdańsk",
    "Szczecin",
]

countries = [
    {"label": "Austria", "value": "Austria"},
    {"label": "Belgia", "value": "Belgia"},
    {"label": "Bułgaria", "value": "Bułgaria"},
    {"label": "Chorwacja", "value": "Chorwacja"},
    {"label": "Cypr", "value": "Cypr"},
    {"label": "Czechy", "value": "Czechy"},
    {"label": "Dania", "value": "Dania"},
    {"label": "Estonia", "value": "Estonia"},
    {"label": "Finlandia", "value": "Finlandia"},
    {"label": "Francja", "value": "Francja"},
    {"label": "Grecja", "value": "Grecja"},
    {"label": "Hiszpania", "value": "Hiszpania"},
    {"label": "Holandia", "value": "Holandia"},
    {"label": "Irlandia", "value": "Irlandia"},
    {"label": "Litwa", "value": "Litwa"},
    {"label": "Luksemburg", "value": "Luksemburg"},
    {"label": "Łotwa", "value": "Łotwa"},
    {"label": "Malta", "value": "Malta"},
    {"label": "Niemcy", "value": "Niemcy"},
    {"label": "Polska", "value": "Polska"},
    {"label": "Portugalia", "value": "Portugalia"},
    {"label": "Rumunia", "value": "Rumunia"},
    {"label": "Słowacja", "value": "Słowacja"},
    {"label": "Słowenia", "value": "Słowenia"},
    {"label": "Szwecja", "value": "Szwecja"},
    {"label": "Węgry", "value": "Węgry"},
    {"label": "Włochy", "value": "Włochy"},
]
