name: Ruff

on: [push, pull_request]

jobs:
  ruff_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruff check
        uses: astral-sh/ruff-action@v1
  ruff_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruff format
        uses: astral-sh/ruff-action@v1
        with:
          args: "format --check"
